mklink /J store ..\..\node_modules\store
mklink /J jquery ..\..\node_modules\jquery
mklink /J jquery-ui ..\..\node_modules\jquery-ui
mklink /J bootstrap ..\..\node_modules\bootstrap
mklink /J select2 ..\..\node_modules\select2
mklink /J select2-bootstrap-theme ..\..\node_modules\select2-bootstrap-theme
mklink /J font-awesome ..\..\node_modules\font-awesome
mklink /J bootstrap-table ..\..\node_modules\bootstrap-table
mklink /J bootstrap-datepicker ..\..\node_modules\bootstrap-datepicker
mklink /J bootstrap-daterangepicker ..\..\node_modules\bootstrap-daterangepicker
mklink /J bootstrap-dialog ..\..\node_modules\bootstrap-dialog
mklink /J lightbox2 ..\..\node_modules\lightbox2
mklink /J jquery-slimscroll ..\..\node_modules\jquery-slimscroll
mklink /J x-editable ..\..\node_modules\x-editable
mklink /J jquery-sparkline ..\..\node_modules\jquery-sparkline
mklink /J jvectormap ..\..\node_modules\jvectormap
mklink /J fastclick ..\..\node_modules\fastclick
mklink /J raphael ..\..\node_modules\raphael
mklink /J moment ..\..\node_modules\moment
mklink /J tableexport.jquery.plugin ..\..\node_modules\tableexport.jquery.plugin
mklink /J cropper ..\..\node_modules\cropper
mklink /J ckeditor ..\..\node_modules\ckeditor
mklink /J icheck ..\..\node_modules\icheck
