#!/bin/sh
ln -s ../../../../node_modules/store store
ln -s ../../../../node_modules/jquery jquery
ln -s ../../../../node_modules/jquery-ui jquery-ui
ln -s ../../../../node_modules/bootstrap bootstrap
ln -s ../../../../node_modules/select2 select2
ln -s ../../../../node_modules/font-awesome font-awesome
ln -s ../../../../node_modules/bootstrap-table bootstrap-table
ln -s ../../../../node_modules/bootstrap-datepicker bootstrap-datepicker
ln -s ../../../../node_modules/bootstrap-daterangepicker bootstrap-daterangepicker
ln -s ../../../../node_modules/bootstrap-dialog bootstrap-dialog
ln -s ../../../../node_modules/lightbox2 lightbox2
ln -s ../../../../node_modules/jquery-slimscroll jquery-slimscroll
ln -s ../../../../node_modules/x-editable x-editable
ln -s ../../../../node_modules/jquery-sparkline jquery-sparkline
ln -s ../../../../node_modules/jvectormap jvectormap
ln -s ../../../../node_modules/fastclick fastclick
ln -s ../../../../node_modules/raphael raphael
ln -s ../../../../node_modules/moment moment
ln -s ../../../../node_modules/tableexport.jquery.plugin tableexport.jquery.plugin
ln -s ../../../../node_modules/cropper cropper
ln -s ../../../../node_modules/crypto-js crypto-js
ln -s ../../../../node_modules/ckeditor ckeditor
ln -s ../../../../node_modules/icheck icheck
